### ISSUE TITLE
Ability to configure own headers for the HTTP request

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy.js#23]
In order to handle non-cookie authentication for API backends (and set the current_user to attach events and visits), we need to be able to add custom headers to the request being sent.

In our case, we are doing Authentication via JSON Web Token passed via either headers or URL parameters. We would need to be able to configure those headers either dynamically on every call or maybe better, after we authenticate the user frontend-side.

**Comment by krsyoung** [comment]
Hey @Startouf,  I'm facing the same problem due to JWT.  I'm using [jwt_sessions](https://github.com/tuwukee/jwt_sessions) as my authentication framework which authentications via a `Authorization` header.

I ended up forking `ajoy.js` and implementing support for `headers` as an additional configuration parameter.  You can take a look here under the `issue_23` branch: https://github.com/krsyoung/ahoy.js/tree/issue_23

It is pretty bad at the moment but works.  In my frontend Vue code I just make a call to set the header once the user has authenticated:

```
// this.$ahoy is my ahoy instance
this.$ahoy.setHeader('Authorization', 'Bearer: ' + accessToken)
```

My situation is even more complicated as I need to decode the token on the backend before I can access the current user.  I solved this by creating a custom user method for ahoy (called `ahoy_user`) that manually performs the decode and then returns the user.

What did you end up doing?   Could my branch work for you?

**Comment by Startouf** [comment]
I'm reading the JWT token + user ID from custom headers named `X-user-Token` and `X-user-email` so I'm not sure your branch would work if you are just reading from `Authorization`

I am using the [`simple_token_authentication` gem ](https://github.com/gonzalo-bulnes/simple_token_authentication)

**Comment by krsyoung** [comment]
Ah, the change I made in my branch is really just to allow ahoy.js to support any arbitrary headers.  I think in your case it would be as simple as:

```
// set customer HTTP headers for ahoy
ahoy.setHeader('X-user-token', 'xxx')
ahoy.setHeader('X-user-email', 'xxx')
```

I also ate a lot of turkey over the past couple of days so I can't really say I'm 100% confident!

**Comment by golmansax** [comment]
@krsyoung I started using your branch and it works great.  One thing is I needed to set `useBeacon` to false to get the headers to send when tracking events.

Since it seems like there's sufficient interest in this feature, can we submit a pull for this?

**Comment by ankane** [comment]
Just added the ability to do `ahoy.configure({headers: ...})` on master.
