### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by akshart** [ankane/ahoy.js#64]
getting TypeError: Illegal invocation
The stack trace’s top layer stops at `window.navigator.sendBeacon(eventsUrl(), index_module_1(data)` which comes from ahoy.js

Calling function is `ahoy.trackView()`
Errors are not confined to any particular browser or device.

**Comment by ankane** [comment]
Hey @akshart, I'm not sure how to reproduce. Can you put together a minimal reproducible example?

**Comment by wenqige** [comment]
This issue is currently quite prevalent in our usage of Ahoy. I don't think it will be very easy to provide a way to reproduce but would it be possible to improving the visibility into the circumstances surrounding the exceptions being thrown? The error it self doesn't give very much info on why it's taking place. Would it be possible to add a try catch to give useful debug output and rethrow, such as an output of eventsUrl() and data and index_module_1's return in order to help us with debugging the Illegal Invocations?

**Comment by pedrocarmona** [comment]
In sentry this error has the following Trace Details

Operation Name: pageload
Status: internal_error
Browser Name: Chrome

![Screenshot 2024-05-23 at 09 45 17](https://github.com/ankane/ahoy.js/assets/2815199/eaf435c9-6793-4259-bfaf-fc7d62c91729)
